import { PROVIDERS } from "./providers.js";
import { buildTtsProviderModels } from "./ttsModels.js";

// Provider models - Single source of truth
// Key = alias (cc, cx, gc, qw, if, ag, gh for OAuth; id for API Key)
// Field "provider" for special cases (e.g. AntiGravity models that call different backends)

export const PROVIDER_MODELS = {
  // OAuth Providers (using alias)
  cc: [  // Claude Code
    { id: "claude-opus-4-7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-5-20251101", name: "Claude 4.5 Opus" },
    { id: "claude-sonnet-4-5-20250929", name: "Claude 4.5 Sonnet" },
    { id: "claude-haiku-4-5-20251001", name: "Claude 4.5 Haiku" },
  ],
  cx: [  // OpenAI Codex
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.4", name: "GPT 5.4" },
    // GPT 5.3 Codex - all thinking levels
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
    { id: "gpt-5.3-codex-xhigh", name: "GPT 5.3 Codex (xHigh)" },
    { id: "gpt-5.3-codex-high", name: "GPT 5.3 Codex (High)" },
    { id: "gpt-5.3-codex-low", name: "GPT 5.3 Codex (Low)" },
    { id: "gpt-5.3-codex-none", name: "GPT 5.3 Codex (None)" },
    { id: "gpt-5.3-codex-spark", name: "GPT 5.3 Codex Spark" },
    // Mini - medium and high only
    { id: "gpt-5.1-codex-mini", name: "GPT 5.1 Codex Mini" },
    { id: "gpt-5.1-codex-mini-high", name: "GPT 5.1 Codex Mini (High)" },
    // Other models
    { id: "gpt-5.2-codex", name: "GPT 5.2 Codex" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "gpt-5.1-codex-max", name: "GPT 5.1 Codex Max" },
    { id: "gpt-5.1-codex", name: "GPT 5.1 Codex" },
    { id: "gpt-5.1", name: "GPT 5.1" },
    { id: "gpt-5-codex", name: "GPT 5 Codex" },
    { id: "gpt-5-codex-mini", name: "GPT 5 Codex Mini" },
    // Image models (uses image_generation tool, requires Plus/Pro plan)
    { id: "gpt-5.4-image", name: "GPT 5.4 Image", type: "image", capabilities: ["text2img", "edit"], params: ["size", "quality", "background", "image_detail", "output_format"] },
    { id: "gpt-5.3-image", name: "GPT 5.3 Image", type: "image", capabilities: ["text2img", "edit"], params: ["size", "quality", "background", "image_detail", "output_format"] },
    { id: "gpt-5.2-image", name: "GPT 5.2 Image", type: "image", capabilities: ["text2img", "edit"], params: ["size", "quality", "background", "image_detail", "output_format"] },
  ],
  gc: [  // Gemini CLI
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gemini-3-pro-preview", name: "Gemini 3 Pro Preview" },
  ],
  qw: [  // Qwen Code
    // { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-coder-flash", name: "Qwen3 Coder Flash" },
    { id: "vision-model", name: "Qwen3 Vision Model" },
    { id: "coder-model", name: "Qwen3.6 Coder Model" },
  ],
  if: [  // iFlow AI
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-max", name: "Qwen3 Max" },
    { id: "qwen3-vl-plus", name: "Qwen3 VL Plus" },
    { id: "qwen3-max-preview", name: "Qwen3 Max Preview" },
    { id: "qwen3-235b", name: "Qwen3 235B A22B" },
    { id: "qwen3-235b-a22b-instruct", name: "Qwen3 235B A22B Instruct" },
    { id: "qwen3-235b-a22b-thinking-2507", name: "Qwen3 235B A22B Thinking" },
    { id: "qwen3-32b", name: "Qwen3 32B" },
    { id: "kimi-k2", name: "Kimi K2" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2 Exp" },
    { id: "deepseek-v3.1", name: "DeepSeek V3.1 Terminus" },
    { id: "deepseek-v3", name: "DeepSeek V3 671B" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "iflow-rome-30ba3b", name: "iFlow ROME" },
  ],
  ag: [  // Antigravity - special case: models call different backends
    { id: "gemini-3.1-pro-high", name: "Gemini 3 Pro High" },
    { id: "gemini-3.1-pro-low", name: "Gemini 3 Pro Low" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash", thinking: false }, // AG strips thinking for this model
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-6-thinking", name: "Claude Opus 4.6 Thinking" },
    { id: "gpt-oss-120b-medium", name: "GPT OSS 120B Medium" },
  ],
  gh: [  // GitHub Copilot - OpenAI models
    { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo" },
    { id: "gpt-4", name: "GPT-4" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o mini" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-5-mini", name: "GPT-5 Mini" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "gpt-5.2-codex", name: "GPT-5.2 Codex" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    // GitHub Copilot - Anthropic models
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-4", name: "Claude Sonnet 4" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    // GitHub Copilot - Google models
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro" },
    // GitHub Copilot - Other models
    { id: "grok-code-fast-1", name: "Grok Code Fast 1" },
    { id: "oswe-vscode-prime", name: "Raptor Mini" },
    { id: "goldeneye-free-auto", name: "GoldenEye" },
    // GitHub Copilot - Embedding models
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small (GitHub)", type: "embedding" },
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large (GitHub)", type: "embedding" },
  ],
  kr: [  // Kiro AI
    // { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "deepseek-3.2", name: "DeepSeek 3.2", strip: ["image", "audio"] },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next", strip: ["image", "audio"] },
    { id: "glm-5", name: "GLM 5" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
  ],
  cu: [  // Cursor IDE
    { id: "default", name: "Auto (Server Picks)" },
    { id: "claude-4.5-opus-high-thinking", name: "Claude 4.5 Opus High Thinking" },
    { id: "claude-4.5-opus-high", name: "Claude 4.5 Opus High" },
    { id: "claude-4.5-sonnet-thinking", name: "Claude 4.5 Sonnet Thinking" },
    { id: "claude-4.5-sonnet", name: "Claude 4.5 Sonnet" },
    { id: "claude-4.5-haiku", name: "Claude 4.5 Haiku" },
    { id: "claude-4.5-opus", name: "Claude 4.5 Opus" },
    { id: "gpt-5.2-codex", name: "GPT 5.2 Codex" },
    { id: "claude-4.6-opus-max", name: "Claude 4.6 Opus Max" },
    { id: "claude-4.6-sonnet-medium-thinking", name: "Claude 4.6 Sonnet Medium Thinking" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
  ],
  kmc: [  // Kimi Coding
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.5-thinking", name: "Kimi K2.5 Thinking" },
    { id: "kimi-latest", name: "Kimi Latest" },
  ],
  kc: [  // KiloCode
    { id: "anthropic/claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
    { id: "anthropic/claude-opus-4-20250514", name: "Claude Opus 4" },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "openai/gpt-4.1", name: "GPT-4.1" },
    { id: "openai/o3", name: "o3" },
    { id: "deepseek/deepseek-chat", name: "DeepSeek Chat" },
    { id: "deepseek/deepseek-reasoner", name: "DeepSeek Reasoner" },
  ],
  "opencode-go": [  // OpenCode Go subscription (API key)
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "qwen3.5-plus", name: "Qwen 3.5 Plus" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "mimo-v2-pro", name: "MiMo V2 Pro" },
    { id: "mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "minimax-m2.7", name: "MiniMax M2.7", targetFormat: "claude" },
    { id: "minimax-m2.5", name: "MiniMax M2.5", targetFormat: "claude" },
  ],
  oc: [  // OpenCode
    // { id: "nemotron-3-super-free", name: "Nemotron 3 Super" },
    // { id: "qwen3.6-plus-free", name: "Qwen 3.6 Plus" },
    // { id: "big-pickle", name: "Big Pickle", targetFormat: "claude" },
    // { id: "minimax-m2.5-free", name: "MiniMax M2.5", targetFormat: "claude" },
    // { id: "trinity-large-preview-free", name: "Trinity Large Preview" },
  ],

  cl: [  // Cline
    { id: "anthropic/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "anthropic/claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "anthropic/claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "openai/gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "openai/gpt-5.4", name: "GPT-5.4" },
    { id: "google/gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    { id: "kwaipilot/kat-coder-pro", name: "KAT Coder Pro" },
  ],

  // API Key Providers (alias = id)
  openai: [
    // Flagship models
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "gpt-5.1", name: "GPT-5.1" },
    { id: "gpt-5", name: "GPT-5" },
    { id: "gpt-5-mini", name: "GPT-5 Mini" },
    { id: "gpt-5-nano", name: "GPT-5 Nano" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
    { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
    // Reasoning models
    { id: "o3", name: "O3" },
    { id: "o3-mini", name: "O3 Mini" },
    { id: "o3-pro", name: "O3 Pro" },
    { id: "o4-mini", name: "O4 Mini" },
    { id: "o1", name: "O1" },
    { id: "o1-mini", name: "O1 Mini" },
    // Embedding models
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large", type: "embedding" },
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small", type: "embedding" },
    { id: "text-embedding-ada-002", name: "Text Embedding Ada 002", type: "embedding" },
    // TTS models
    { id: "tts-1", name: "TTS-1", type: "tts" },
    { id: "tts-1-hd", name: "TTS-1 HD", type: "tts" },
    { id: "gpt-4o-mini-tts", name: "GPT-4o Mini TTS", type: "tts" },
    // Image models
    { id: "gpt-image-1", name: "GPT Image 1", type: "image", params: ["n", "size", "quality", "response_format"] },
    { id: "dall-e-3", name: "DALL-E 3", type: "image", params: ["size", "quality", "style", "response_format"] },
    { id: "dall-e-2", name: "DALL-E 2", type: "image", params: ["n", "size", "response_format"] },
  ],
  anthropic: [
    { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
    { id: "claude-opus-4-20250514", name: "Claude Opus 4" },
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet" },
  ],
  gemini: [
    // Gemini 3.1 series
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    // Gemini 3 series
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    // Gemini 2.5 series
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite" },
    // Gemini 2.0 series (retiring June 1, 2026)
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash" },
    { id: "gemini-2.0-flash-lite", name: "Gemini 2.0 Flash Lite" },
    { id: "gemma-4-31b-it", name: "Gemma 4 31B IT" },

    // Embedding models
    { id: "gemini-embedding-2-preview", name: "Gemini Embedding 2 Preview", type: "embedding" },
    { id: "gemini-embedding-001", name: "Gemini Embedding 001", type: "embedding" },
    { id: "text-embedding-005", name: "Text Embedding 005", type: "embedding" },
    { id: "text-embedding-004", name: "Text Embedding 004 (Legacy)", type: "embedding" },
    // Image models (Nano Banana)
    { id: "gemini-3.1-flash-image-preview", name: "Gemini 3.1 Flash Image (Nano Banana 2)", type: "image", params: [] },
    { id: "gemini-3-pro-image-preview", name: "Gemini 3 Pro Image (Nano Banana Pro)", type: "image", params: [] },
    { id: "gemini-2.5-flash-image", name: "Gemini 2.5 Flash Image (Nano Banana)", type: "image", params: [] },
  ],
  openrouter: [
    // Embedding models
    { id: "openai/text-embedding-3-large", name: "OpenAI Text Embedding 3 Large", type: "embedding" },
    { id: "openai/text-embedding-3-small", name: "OpenAI Text Embedding 3 Small", type: "embedding" },
    { id: "openai/text-embedding-ada-002", name: "OpenAI Text Embedding Ada 002", type: "embedding" },
    { id: "qwen/qwen3-embedding-8b", name: "Qwen3 Embedding 8B", type: "embedding" },
    { id: "perplexity/pplx-embed-v1-4b", name: "Perplexity Embed V1 4B", type: "embedding" },
    { id: "perplexity/pplx-embed-v1-0.6b", name: "Perplexity Embed V1 0.6B", type: "embedding" },
    { id: "nvidia/llama-nemotron-embed-vl-1b-v2:free", name: "NVIDIA Nemotron Embed VL 1B V2 (Free)", type: "embedding" },
    // TTS models
    { id: "openai/gpt-4o-mini-tts", name: "GPT-4o Mini TTS", type: "tts" },
    { id: "openai/tts-1-hd",        name: "TTS-1 HD",        type: "tts" },
    { id: "openai/tts-1",           name: "TTS-1",           type: "tts" },
    // Image models
    { id: "openai/dall-e-3", name: "DALL-E 3 (via OpenRouter)", type: "image", params: ["size", "quality", "style", "response_format"] },
    { id: "openai/gpt-image-1", name: "GPT Image 1 (via OpenRouter)", type: "image", params: ["n", "size", "quality", "response_format"] },
    { id: "google/imagen-3.0-generate-002", name: "Imagen 3 (via OpenRouter)", type: "image", params: ["n", "size"] },
    { id: "black-forest-labs/FLUX.1-schnell", name: "FLUX.1 Schnell (via OpenRouter)", type: "image", params: ["n", "size"] },
  ],
  glm: [
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "glm-4.6v", name: "GLM 4.6V (Vision)" },
  ],
  "glm-cn": [
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-4.7", name: "GLM-4.7" },
    { id: "glm-4.6", name: "GLM-4.6" },
    { id: "glm-4.5-air", name: "GLM-4.5-Air" },
  ],
  kimi: [
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.5-thinking", name: "Kimi K2.5 Thinking" },
    { id: "kimi-latest", name: "Kimi Latest" },
  ],
  minimax: [
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "MiniMax-M2.1", name: "MiniMax M2.1" },
    // Image models
    { id: "minimax-image-01", name: "MiniMax Image 01", type: "image", params: ["n", "size", "response_format"] },
  ],
  blackbox: [
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o mini" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6 (Legacy)" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6 (Legacy)" },
    { id: "deepseek-chat", name: "DeepSeek Chat" },
    { id: "deepseek-v3-671b", name: "DeepSeek V3 671B" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "o1", name: "OpenAI o1" },
    { id: "o3-mini", name: "OpenAI o3-mini" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-max", name: "Qwen3 Max" },
    { id: "qwen3-vl-plus", name: "Qwen3 VL Plus" },
  ],
  "minimax-cn": [
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "MiniMax-M2.1", name: "MiniMax M2.1" },
  ],
  alicode: [
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "qwen3-max-2026-01-23", name: "Qwen3 Max" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "glm-4.7", name: "GLM 4.7" },
  ],
  "alicode-intl": [
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "glm-4.7", name: "GLM 4.7" },
  ],
  "volcengine-ark": [
    { id: "Doubao-Seed-2.0-Code", name: "Doubao-Seed-2.0-Code" },
    { id: "Doubao-Seed-2.0-pro", name: "Doubao-Seed-2.0-pro" },
    { id: "Doubao-Seed-2.0-lite", name: "Doubao-Seed-2.0-lite" },
    { id: "Doubao-Seed-Code", name: "Doubao-Seed-Code" },
    { id: "GLM-5.1", name: "GLM-5.1" },
    { id: "MiniMax-M2.7", name: "MiniMax-M2.7" },
    { id: "Kimi-K2.6", name: "Kimi-K2.6" },
    { id: "MiniMax-M2.5", name: "MiniMax-M2.5" },
    { id: "Kimi-K2.5", name: "Kimi-K2.5" },
    { id: "GLM-4.7", name: "GLM-4.7" },
    { id: "DeepSeek-V3.2", name: "DeepSeek-V3.2" },
  ],
  "cloudflare-ai": [
    { id: "@cf/moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "@cf/zai-org/glm-4.7-flash", name: "GLM 4.7 Flash" },
  ],
  byteplus: [
    { id: "seed-2-0-pro-260328", name: "Seed 2.0 Pro" },
    { id: "seed-2-0-code-preview-260328", name: "Seed 2.0 Code Preview" },
    { id: "seed-2-0-mini-260215", name: "Seed 2.0 Mini" },
    { id: "seed-2-0-lite-260228", name: "Seed 2.0 Lite" },
    { id: "kimi-k2-thinking-251104", name: "Kimi K2 Thinking" },
    { id: "glm-4-7-251222", name: "GLM 4.7" },
    { id: "gpt-oss-120b-250805", name: "GPT-OSS-120B" },
  ],
  deepseek: [
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-chat", name: "DeepSeek V3.2 Chat" },
    { id: "deepseek-reasoner", name: "DeepSeek V3.2 Reasoner" },
  ],
  groq: [
    { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B" },
    { id: "meta-llama/llama-4-maverick-17b-128e-instruct", name: "Llama 4 Maverick" },
    { id: "qwen/qwen3-32b", name: "Qwen3 32B" },
    { id: "openai/gpt-oss-120b", name: "GPT-OSS 120B" },
  ],
  xai: [
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-fast-reasoning", name: "Grok 4 Fast Reasoning" },
    { id: "grok-code-fast-1", name: "Grok Code Fast" },
    { id: "grok-3", name: "Grok 3" },
  ],
  mistral: [
    { id: "mistral-large-latest", name: "Mistral Large 3" },
    { id: "codestral-latest", name: "Codestral" },
    { id: "mistral-medium-latest", name: "Mistral Medium 3" },
    { id: "mistral-embed", name: "Mistral Embed", type: "embedding" },
  ],
  perplexity: [
    { id: "sonar-pro", name: "Sonar Pro" },
    { id: "sonar", name: "Sonar" },
  ],
  together: [
    { id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", name: "Llama 3.3 70B Turbo" },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "Qwen/Qwen3-235B-A22B", name: "Qwen3 235B" },
    { id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", name: "Llama 4 Maverick" },
    { id: "BAAI/bge-large-en-v1.5", name: "BGE Large EN v1.5", type: "embedding" },
    { id: "togethercomputer/m2-bert-80M-8k-retrieval", name: "M2 BERT 80M 8K", type: "embedding" },
  ],
  fireworks: [
    { id: "accounts/fireworks/models/deepseek-v3p1", name: "DeepSeek V3.1" },
    { id: "accounts/fireworks/models/llama-v3p3-70b-instruct", name: "Llama 3.3 70B" },
    { id: "accounts/fireworks/models/qwen3-235b-a22b", name: "Qwen3 235B" },
    { id: "nomic-ai/nomic-embed-text-v1.5", name: "Nomic Embed Text v1.5", type: "embedding" },
  ],
  cerebras: [
    { id: "gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "zai-glm-4.7", name: "ZAI GLM 4.7" },
    { id: "llama-3.3-70b", name: "Llama 3.3 70B" },
    { id: "llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout" },
    { id: "qwen-3-235b-a22b-instruct-2507", name: "Qwen3 235B A22B" },
    { id: "qwen-3-32b", name: "Qwen3 32B" },
  ],
  cohere: [
    { id: "command-r-plus-08-2024", name: "Command R+ (Aug 2024)" },
    { id: "command-r-08-2024", name: "Command R (Aug 2024)" },
    { id: "command-a-03-2025", name: "Command A (Mar 2025)" },
  ],
  nvidia: [
    { id: "minimaxai/minimax-m2.7", name: "Minimax M2.7" },
    { id: "z-ai/glm4.7", name: "GLM 4.7" },
    { id: "nvidia/nv-embedqa-e5-v5", name: "NV EmbedQA E5 v5", type: "embedding" },
  ],
  nebius: [
    { id: "meta-llama/Llama-3.3-70B-Instruct", name: "Llama 3.3 70B Instruct" },
    { id: "Qwen/Qwen3-Embedding-8B", name: "Qwen3 Embedding 8B", type: "embedding" },
  ],
  "voyage-ai": [
    { id: "voyage-3-large", name: "Voyage 3 Large", type: "embedding" },
    { id: "voyage-3.5", name: "Voyage 3.5", type: "embedding" },
    { id: "voyage-3.5-lite", name: "Voyage 3.5 Lite", type: "embedding" },
    { id: "voyage-code-3", name: "Voyage Code 3", type: "embedding" },
    { id: "voyage-finance-2", name: "Voyage Finance 2", type: "embedding" },
    { id: "voyage-law-2", name: "Voyage Law 2", type: "embedding" },
    { id: "voyage-multilingual-2", name: "Voyage Multilingual 2", type: "embedding" },
  ],
  siliconflow: [
    { id: "deepseek-ai/DeepSeek-V3.2", name: "DeepSeek V3.2" },
    { id: "deepseek-ai/DeepSeek-V3.1", name: "DeepSeek V3.1" },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "Qwen/Qwen3-235B-A22B-Instruct-2507", name: "Qwen3 235B" },
    { id: "Qwen/Qwen3-Coder-480B-A35B-Instruct", name: "Qwen3 Coder 480B" },
    { id: "Qwen/Qwen3-32B", name: "Qwen3 32B" },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5" },
    { id: "zai-org/GLM-4.7", name: "GLM 4.7" },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "baidu/ERNIE-4.5-300B-A47B", name: "ERNIE 4.5 300B" },
  ],
  "xiaomi-mimo": [
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "mimo-v2-flash", name: "MiMo V2 Flash" },
  ],
  hyperbolic: [
    { id: "Qwen/QwQ-32B", name: "QwQ 32B" },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "deepseek-ai/DeepSeek-V3", name: "DeepSeek V3" },
    { id: "meta-llama/Llama-3.3-70B-Instruct", name: "Llama 3.3 70B" },
    { id: "meta-llama/Llama-3.2-3B-Instruct", name: "Llama 3.2 3B" },
    { id: "Qwen/Qwen2.5-72B-Instruct", name: "Qwen 2.5 72B" },
    { id: "Qwen/Qwen2.5-Coder-32B-Instruct", name: "Qwen 2.5 Coder 32B" },
    { id: "NousResearch/Hermes-3-Llama-3.1-70B", name: "Hermes 3 70B" },
  ],
  ollama: [
    { id: "gpt-oss:120b", name: "GPT OSS 120B" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "qwen3.5", name: "Qwen3.5" },
  ],
  vertex: [
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
  ],
  "vertex-partner": [
    { id: "deepseek-ai/deepseek-v3.2-maas", name: "DeepSeek V3.2 (Vertex)" },
    { id: "qwen/qwen3-next-80b-a3b-thinking-maas", name: "Qwen3 Next 80B Thinking (Vertex)" },
    { id: "qwen/qwen3-next-80b-a3b-instruct-maas", name: "Qwen3 Next 80B Instruct (Vertex)" },
    { id: "zai-org/glm-5-maas", name: "GLM-5 (Vertex)" },
  ],
  "grok-web": [
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-3-mini", name: "Grok 3 Mini (Thinking)" },
    { id: "grok-3-thinking", name: "Grok 3 Thinking" },
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-mini", name: "Grok 4 Mini (Thinking)" },
    { id: "grok-4-thinking", name: "Grok 4 Thinking" },
    { id: "grok-4-heavy", name: "Grok 4 Heavy (SuperGrok)" },
    { id: "grok-4.1-mini", name: "Grok 4.1 Mini (Thinking)" },
    { id: "grok-4.1-fast", name: "Grok 4.1 Fast" },
    { id: "grok-4.1-expert", name: "Grok 4.1 Expert" },
    { id: "grok-4.1-thinking", name: "Grok 4.1 Thinking" },
    { id: "grok-4.2", name: "Grok 4.2 (4.20 Beta)" },
  ],
  "perplexity-web": [
    { id: "pplx-auto", name: "Perplexity Auto (Free)" },
    { id: "pplx-sonar", name: "Perplexity Sonar" },
    { id: "pplx-gpt", name: "GPT-5.4 (via Perplexity)" },
    { id: "pplx-gemini", name: "Gemini 3.1 Pro (via Perplexity)" },
    { id: "pplx-sonnet", name: "Claude Sonnet 4.6 (via Perplexity)" },
    { id: "pplx-opus", name: "Claude Opus 4.6 (via Perplexity)" },
    { id: "pplx-nemotron", name: "Nemotron 3 Super (via Perplexity)" },
  ],

  // Unified gateway providers (passthrough — any model id works)
  agentrouter: [
    { id: "claude-3-5-haiku-20241022", name: "Claude 3 5 Haiku 20241022" },
    { id: "claude-3-5-sonnet-20240620", name: "Claude 3 5 Sonnet 20240620" },
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3 5 Sonnet 20241022" },
    { id: "claude-3-7-sonnet-20250219", name: "Claude 3 7 Sonnet 20250219" },
    { id: "claude-3-7-sonnet-20250219-thinking", name: "Claude 3 7 Sonnet 20250219 Thinking" },
    { id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4 5 20251001" },
    { id: "claude-opus-4-20250514", name: "Claude Opus 4 20250514" },
    { id: "claude-opus-4-20250514-thinking", name: "Claude Opus 4 20250514 Thinking" },
    { id: "claude-opus-4-5-20251101", name: "Claude Opus 4 5 20251101" },
    { id: "claude-opus-4-6", name: "Claude Opus 4 6" },
    { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4 20250514" },
    { id: "claude-sonnet-4-20250514-thinking", name: "Claude Sonnet 4 20250514 Thinking" },
    { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4 5 20250929" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4 6" },
    { id: "deepseek-r1-0528", name: "Deepseek R1 0528" },
    { id: "deepseek-v3.1", name: "Deepseek V3.1" },
    { id: "deepseek-v3.2", name: "Deepseek V3.2" },
    { id: "glm-4.5", name: "Glm 4.5" },
    { id: "glm-4.6", name: "Glm 4.6" },
    { id: "glm-5.1", name: "Glm 5.1" },
  ],
  bluesminds: [
    { id: "01-ai/yi-large", name: "Yi Large" },
    { id: "MiniMax-M2", name: "MiniMax M2" },
    { id: "MiniMax-M2.1", name: "MiniMax M2.1" },
    { id: "MiniMax-M2.1-lightning", name: "MiniMax M2.1 Lightning" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "abacusai/dracarys-llama-3.1-70b-instruct", name: "Dracarys Llama 3.1 70b Instruct" },
    { id: "adept/fuyu-8b", name: "Fuyu 8b" },
    { id: "ai21labs/jamba-1.5-large-instruct", name: "Jamba 1.5 Large Instruct" },
    { id: "ai21labs/jamba-1.5-mini-instruct", name: "Jamba 1.5 Mini Instruct" },
    { id: "aisingapore/sea-lion-7b-instruct", name: "Sea Lion 7b Instruct" },
    { id: "baai/bge-m3", name: "Bge M3" },
    { id: "baichuan-inc/baichuan2-13b-chat", name: "Baichuan2 13b Chat" },
    { id: "bigcode/starcoder2-15b", name: "Starcoder2 15b" },
    { id: "bigcode/starcoder2-7b", name: "Starcoder2 7b" },
    { id: "bytedance/seed-oss-36b-instruct", name: "Seed Oss 36b Instruct" },
    { id: "claude-3-5-sonnet-20240620", name: "Claude 3 5 Sonnet 20240620" },
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3 5 Sonnet 20241022" },
    { id: "claude-3-haiku", name: "Claude 3 Haiku" },
    { id: "claude-3-haiku-20240307", name: "Claude 3 Haiku 20240307" },
    { id: "claude-3-opus-20240229", name: "Claude 3 Opus 20240229" },
    { id: "claude-opus", name: "Claude Opus" },
    { id: "claude-sonnet-4-5-20250929", name: "Claude Sonnet 4 5 20250929" },
    { id: "claude-sonnet-4-5-20250929-v1", name: "Claude Sonnet 4 5 20250929 V1" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4 6" },
    { id: "databricks/dbrx-instruct", name: "Dbrx Instruct" },
    { id: "deepseek-ai/DeepSeek-V3.1-Terminus", name: "DeepSeek V3.1 Terminus" },
    { id: "deepseek-ai/DeepSeek-V4-Pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-ai/deepseek-coder-6.7b-instruct", name: "Deepseek Coder 6.7b Instruct" },
    { id: "deepseek-ai/deepseek-r1-distill-llama-8b", name: "Deepseek R1 Distill Llama 8b" },
    { id: "deepseek-ai/deepseek-r1-distill-qwen-14b", name: "Deepseek R1 Distill Qwen 14b" },
    { id: "deepseek-ai/deepseek-r1-distill-qwen-32b", name: "Deepseek R1 Distill Qwen 32b" },
    { id: "deepseek-ai/deepseek-r1-distill-qwen-7b", name: "Deepseek R1 Distill Qwen 7b" },
    { id: "deepseek-ai/deepseek-v3.1", name: "Deepseek V3.1" },
    { id: "deepseek-ai/deepseek-v3.1-terminus", name: "Deepseek V3.1 Terminus" },
    { id: "deepseek-ai/deepseek-v3.2", name: "Deepseek V3.2" },
    { id: "deepseek-ai/deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "deepseek-chat", name: "Deepseek Chat" },
    { id: "deepseek-reasoner", name: "Deepseek Reasoner" },
    { id: "glm-4.6", name: "Glm 4.6" },
    { id: "google/codegemma-1.1-7b", name: "Codegemma 1.1 7b" },
    { id: "google/codegemma-7b", name: "Codegemma 7b" },
    { id: "google/deplot", name: "Deplot" },
    { id: "google/gemma-2-27b-it", name: "Gemma 2 27b It" },
    { id: "google/gemma-2-2b-it", name: "Gemma 2 2b It" },
    { id: "google/gemma-2-9b-it", name: "Gemma 2 9b It" },
    { id: "google/gemma-2b", name: "Gemma 2b" },
    { id: "google/gemma-3-12b-it", name: "Gemma 3 12b It" },
    { id: "google/gemma-3-1b-it", name: "Gemma 3 1b It" },
    { id: "google/gemma-3-27b-it", name: "Gemma 3 27b It" },
    { id: "google/gemma-3-4b-it", name: "Gemma 3 4b It" },
    { id: "google/gemma-3n-e2b-it", name: "Gemma 3n E2b It" },
    { id: "google/gemma-3n-e4b-it", name: "Gemma 3n E4b It" },
    { id: "google/gemma-4-31b-it", name: "Gemma 4 31b It" },
    { id: "google/gemma-7b", name: "Gemma 7b" },
    { id: "google/paligemma", name: "Paligemma" },
    { id: "google/recurrentgemma-2b", name: "Recurrentgemma 2b" },
    { id: "google/shieldgemma-9b", name: "Shieldgemma 9b" },
    { id: "gotocompany/gemma-2-9b-cpt-sahabatai-instruct", name: "Gemma 2 9b Cpt Sahabatai Instruct" },
    { id: "gpt-3.5-turbo-0613", name: "Gpt 3.5 Turbo 0613" },
    { id: "gpt-4o", name: "Gpt 4o" },
    { id: "gpt-4o-mini", name: "Gpt 4o Mini" },
    { id: "gpt-5-nano", name: "Gpt 5 Nano" },
    { id: "gpt-oss-120b", name: "Gpt Oss 120b" },
    { id: "ibm/granite-3.0-3b-a800m-instruct", name: "Granite 3.0 3b A800m Instruct" },
    { id: "ibm/granite-3.0-8b-instruct", name: "Granite 3.0 8b Instruct" },
    { id: "ibm/granite-3.3-8b-instruct", name: "Granite 3.3 8b Instruct" },
    { id: "ibm/granite-34b-code-instruct", name: "Granite 34b Code Instruct" },
    { id: "ibm/granite-8b-code-instruct", name: "Granite 8b Code Instruct" },
    { id: "ibm/granite-guardian-3.0-8b", name: "Granite Guardian 3.0 8b" },
    { id: "igenius/colosseum_355b_instruct_16k", name: "Colosseum_355b_instruct_16k" },
    { id: "igenius/italia_10b_instruct_16k", name: "Italia_10b_instruct_16k" },
    { id: "institute-of-science-tokyo/llama-3.1-swallow-70b-instruct-v0.1", name: "Llama 3.1 Swallow 70b Instruct V0.1" },
    { id: "institute-of-science-tokyo/llama-3.1-swallow-8b-instruct-v0.1", name: "Llama 3.1 Swallow 8b Instruct V0.1" },
    { id: "kimi-2.5-turbo", name: "Kimi 2.5 Turbo" },
    { id: "kimi-2.5-ultra", name: "Kimi 2.5 Ultra" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "marin/marin-8b-instruct", name: "Marin 8b Instruct" },
    { id: "mediatek/breeze-7b-instruct", name: "Breeze 7b Instruct" },
    { id: "meta/codellama-70b", name: "Codellama 70b" },
    { id: "meta/llama-3.1-405b-instruct", name: "Llama 3.1 405b Instruct" },
    { id: "meta/llama-3.1-70b-instruct", name: "Llama 3.1 70b Instruct" },
    { id: "meta/llama-3.1-8b-instruct", name: "Llama 3.1 8b Instruct" },
    { id: "meta/llama-3.2-11b-vision-instruct", name: "Llama 3.2 11b Vision Instruct" },
    { id: "meta/llama-3.2-1b-instruct", name: "Llama 3.2 1b Instruct" },
    { id: "meta/llama-3.2-3b-instruct", name: "Llama 3.2 3b Instruct" },
    { id: "meta/llama-3.2-90b-vision-instruct", name: "Llama 3.2 90b Vision Instruct" },
    { id: "meta/llama-3.3-70b-instruct", name: "Llama 3.3 70b Instruct" },
    { id: "meta/llama-4-maverick-17b-128e-instruct", name: "Llama 4 Maverick 17b 128e Instruct" },
    { id: "meta/llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout 17b 16e Instruct" },
    { id: "meta/llama-guard-4-12b", name: "Llama Guard 4 12b" },
    { id: "meta/llama2-70b", name: "Llama2 70b" },
    { id: "meta/llama3-70b-instruct", name: "Llama3 70b Instruct" },
    { id: "meta/llama3-8b-instruct", name: "Llama3 8b Instruct" },
    { id: "microsoft/kosmos-2", name: "Kosmos 2" },
    { id: "microsoft/phi-3-medium-128k-instruct", name: "Phi 3 Medium 128k Instruct" },
    { id: "microsoft/phi-3-medium-4k-instruct", name: "Phi 3 Medium 4k Instruct" },
    { id: "microsoft/phi-3-mini-128k-instruct", name: "Phi 3 Mini 128k Instruct" },
    { id: "microsoft/phi-3-mini-4k-instruct", name: "Phi 3 Mini 4k Instruct" },
    { id: "microsoft/phi-3-small-128k-instruct", name: "Phi 3 Small 128k Instruct" },
    { id: "microsoft/phi-3-small-8k-instruct", name: "Phi 3 Small 8k Instruct" },
    { id: "microsoft/phi-3-vision-128k-instruct", name: "Phi 3 Vision 128k Instruct" },
    { id: "microsoft/phi-3.5-mini-instruct", name: "Phi 3.5 Mini Instruct" },
    { id: "microsoft/phi-3.5-moe-instruct", name: "Phi 3.5 Moe Instruct" },
    { id: "microsoft/phi-3.5-vision-instruct", name: "Phi 3.5 Vision Instruct" },
    { id: "microsoft/phi-4-mini-flash-reasoning", name: "Phi 4 Mini Flash Reasoning" },
    { id: "microsoft/phi-4-mini-instruct", name: "Phi 4 Mini Instruct" },
    { id: "microsoft/phi-4-multimodal-instruct", name: "Phi 4 Multimodal Instruct" },
    { id: "minimaxai/minimax-m2.5", name: "Minimax M2.5" },
    { id: "minimaxai/minimax-m2.7", name: "Minimax M2.7" },
    { id: "mistralai/codestral-22b-instruct-v0.1", name: "Codestral 22b Instruct V0.1" },
    { id: "mistralai/devstral-2-123b-instruct-2512", name: "Devstral 2 123b Instruct 2512" },
    { id: "mistralai/magistral-small-2506", name: "Magistral Small 2506" },
    { id: "mistralai/mamba-codestral-7b-v0.1", name: "Mamba Codestral 7b V0.1" },
    { id: "mistralai/mathstral-7b-v0.1", name: "Mathstral 7b V0.1" },
    { id: "mistralai/ministral-14b-instruct-2512", name: "Ministral 14b Instruct 2512" },
    { id: "mistralai/mistral-7b-instruct-v0.2", name: "Mistral 7b Instruct V0.2" },
    { id: "mistralai/mistral-7b-instruct-v0.3", name: "Mistral 7b Instruct V0.3" },
    { id: "mistralai/mistral-large", name: "Mistral Large" },
    { id: "mistralai/mistral-large-2-instruct", name: "Mistral Large 2 Instruct" },
    { id: "mistralai/mistral-large-3-675b-instruct-2512", name: "Mistral Large 3 675b Instruct 2512" },
    { id: "mistralai/mistral-medium-3-instruct", name: "Mistral Medium 3 Instruct" },
    { id: "mistralai/mistral-nemotron", name: "Mistral Nemotron" },
    { id: "mistralai/mistral-small-24b-instruct", name: "Mistral Small 24b Instruct" },
    { id: "mistralai/mistral-small-3.1-24b-instruct-2503", name: "Mistral Small 3.1 24b Instruct 2503" },
    { id: "mistralai/mistral-small-4-119b-2603", name: "Mistral Small 4 119b 2603" },
    { id: "mistralai/mixtral-8x22b-instruct-v0.1", name: "Mixtral 8x22b Instruct V0.1" },
    { id: "mistralai/mixtral-8x22b-v0.1", name: "Mixtral 8x22b V0.1" },
    { id: "mistralai/mixtral-8x7b-instruct-v0.1", name: "Mixtral 8x7b Instruct V0.1" },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5" },
    { id: "moonshotai/kimi-k2-instruct", name: "Kimi K2 Instruct" },
    { id: "moonshotai/kimi-k2-instruct-0905", name: "Kimi K2 Instruct 0905" },
    { id: "moonshotai/kimi-k2-thinking", name: "Kimi K2 Thinking" },
    { id: "moonshotai/kimi-k2.5", name: "Kimi K2.5" },
    { id: "nv-mistralai/mistral-nemo-12b-instruct", name: "Mistral Nemo 12b Instruct" },
    { id: "nvidia/cosmos-reason2-8b", name: "Cosmos Reason2 8b" },
    { id: "nvidia/embed-qa-4", name: "Embed Qa 4" },
    { id: "nvidia/gliner-pii", name: "Gliner Pii" },
    { id: "nvidia/llama-3.1-nemoguard-8b-content-safety", name: "Llama 3.1 Nemoguard 8b Content Safety" },
    { id: "nvidia/llama-3.1-nemoguard-8b-topic-control", name: "Llama 3.1 Nemoguard 8b Topic Control" },
    { id: "nvidia/llama-3.1-nemotron-51b-instruct", name: "Llama 3.1 Nemotron 51b Instruct" },
    { id: "nvidia/llama-3.1-nemotron-70b-instruct", name: "Llama 3.1 Nemotron 70b Instruct" },
    { id: "nvidia/llama-3.1-nemotron-70b-reward", name: "Llama 3.1 Nemotron 70b Reward" },
    { id: "nvidia/llama-3.1-nemotron-nano-4b-v1.1", name: "Llama 3.1 Nemotron Nano 4b V1.1" },
    { id: "nvidia/llama-3.1-nemotron-nano-8b-v1", name: "Llama 3.1 Nemotron Nano 8b V1" },
    { id: "nvidia/llama-3.1-nemotron-nano-vl-8b-v1", name: "Llama 3.1 Nemotron Nano Vl 8b V1" },
    { id: "nvidia/llama-3.1-nemotron-safety-guard-8b-v3", name: "Llama 3.1 Nemotron Safety Guard 8b V3" },
    { id: "nvidia/llama-3.1-nemotron-ultra-253b-v1", name: "Llama 3.1 Nemotron Ultra 253b V1" },
    { id: "nvidia/llama-3.2-nemoretriever-1b-vlm-embed-v1", name: "Llama 3.2 Nemoretriever 1b Vlm Embed V1" },
    { id: "nvidia/llama-3.2-nemoretriever-300m-embed-v1", name: "Llama 3.2 Nemoretriever 300m Embed V1" },
    { id: "nvidia/llama-3.2-nv-embedqa-1b-v1", name: "Llama 3.2 Nv Embedqa 1b V1" },
    { id: "nvidia/llama-3.2-nv-embedqa-1b-v2", name: "Llama 3.2 Nv Embedqa 1b V2" },
    { id: "nvidia/llama-3.3-nemotron-super-49b-v1", name: "Llama 3.3 Nemotron Super 49b V1" },
    { id: "nvidia/llama-3.3-nemotron-super-49b-v1.5", name: "Llama 3.3 Nemotron Super 49b V1.5" },
    { id: "nvidia/llama-nemotron-embed-1b-v2", name: "Llama Nemotron Embed 1b V2" },
    { id: "nvidia/llama-nemotron-embed-vl-1b-v2", name: "Llama Nemotron Embed Vl 1b V2" },
    { id: "nvidia/llama3-chatqa-1.5-70b", name: "Llama3 Chatqa 1.5 70b" },
    { id: "nvidia/llama3-chatqa-1.5-8b", name: "Llama3 Chatqa 1.5 8b" },
    { id: "nvidia/mistral-nemo-minitron-8b-8k-instruct", name: "Mistral Nemo Minitron 8b 8k Instruct" },
    { id: "nvidia/mistral-nemo-minitron-8b-base", name: "Mistral Nemo Minitron 8b Base" },
    { id: "nvidia/nemoretriever-parse", name: "Nemoretriever Parse" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "Nemotron 3 Nano 30b A3b" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "Nemotron 3 Super 120b A12b" },
    { id: "nvidia/nemotron-4-340b-instruct", name: "Nemotron 4 340b Instruct" },
    { id: "nvidia/nemotron-4-340b-reward", name: "Nemotron 4 340b Reward" },
    { id: "nvidia/nemotron-4-mini-hindi-4b-instruct", name: "Nemotron 4 Mini Hindi 4b Instruct" },
    { id: "nvidia/nemotron-content-safety-reasoning-4b", name: "Nemotron Content Safety Reasoning 4b" },
    { id: "nvidia/nemotron-mini-4b-instruct", name: "Nemotron Mini 4b Instruct" },
    { id: "nvidia/nemotron-nano-12b-v2-vl", name: "Nemotron Nano 12b V2 Vl" },
    { id: "nvidia/nemotron-nano-3-30b-a3b", name: "Nemotron Nano 3 30b A3b" },
    { id: "nvidia/nemotron-parse", name: "Nemotron Parse" },
    { id: "nvidia/neva-22b", name: "Neva 22b" },
    { id: "nvidia/nv-embed-v1", name: "Nv Embed V1" },
    { id: "nvidia/nv-embedcode-7b-v1", name: "Nv Embedcode 7b V1" },
    { id: "nvidia/nv-embedqa-e5-v5", name: "Nv Embedqa E5 V5" },
    { id: "nvidia/nv-embedqa-mistral-7b-v2", name: "Nv Embedqa Mistral 7b V2" },
    { id: "nvidia/nvclip", name: "Nvclip" },
    { id: "nvidia/nvidia-nemotron-nano-9b-v2", name: "Nvidia Nemotron Nano 9b V2" },
    { id: "nvidia/riva-translate-4b-instruct", name: "Riva Translate 4b Instruct" },
    { id: "nvidia/riva-translate-4b-instruct-v1.1", name: "Riva Translate 4b Instruct V1.1" },
    { id: "nvidia/streampetr", name: "Streampetr" },
    { id: "nvidia/usdcode-llama-3.1-70b-instruct", name: "Usdcode Llama 3.1 70b Instruct" },
    { id: "nvidia/vila", name: "Vila" },
    { id: "openai/gpt-oss-120b", name: "Gpt Oss 120b" },
    { id: "openai/gpt-oss-20b", name: "Gpt Oss 20b" },
    { id: "openai/zai-org/GLM-4.7", name: "Zai Org/GLM 4.7" },
    { id: "opengpt-x/teuken-7b-instruct-commercial-v0.4", name: "Teuken 7b Instruct Commercial V0.4" },
    { id: "qwen-coder", name: "Qwen Coder" },
    { id: "qwen/qwen2-7b-instruct", name: "Qwen2 7b Instruct" },
    { id: "qwen/qwen2.5-7b-instruct", name: "Qwen2.5 7b Instruct" },
    { id: "qwen/qwen2.5-coder-32b-instruct", name: "Qwen2.5 Coder 32b Instruct" },
    { id: "qwen/qwen2.5-coder-7b-instruct", name: "Qwen2.5 Coder 7b Instruct" },
    { id: "qwen/qwen3-coder-480b-a35b-instruct", name: "Qwen3 Coder 480b A35b Instruct" },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "Qwen3 Next 80b A3b Instruct" },
    { id: "qwen/qwen3-next-80b-a3b-thinking", name: "Qwen3 Next 80b A3b Thinking" },
    { id: "qwen/qwen3.5-122b-a10b", name: "Qwen3.5 122b A10b" },
    { id: "qwen/qwen3.5-397b-a17b", name: "Qwen3.5 397b A17b" },
    { id: "qwen/qwq-32b", name: "Qwq 32b" },
    { id: "rakuten/rakutenai-7b-chat", name: "Rakutenai 7b Chat" },
    { id: "rakuten/rakutenai-7b-instruct", name: "Rakutenai 7b Instruct" },
    { id: "sarvamai/sarvam-m", name: "Sarvam M" },
    { id: "snowflake/arctic-embed-l", name: "Arctic Embed L" },
    { id: "speakleash/bielik-11b-v2.3-instruct", name: "Bielik 11b V2.3 Instruct" },
    { id: "speakleash/bielik-11b-v2.6-instruct", name: "Bielik 11b V2.6 Instruct" },
    { id: "stepfun-ai/step-3.5-flash", name: "Step 3.5 Flash" },
    { id: "stockmark/stockmark-2-100b-instruct", name: "Stockmark 2 100b Instruct" },
    { id: "thudm/chatglm3-6b", name: "Chatglm3 6b" },
    { id: "tiiuae/falcon3-7b-instruct", name: "Falcon3 7b Instruct" },
    { id: "tokyotech-llm/llama-3-swallow-70b-instruct-v0.1", name: "Llama 3 Swallow 70b Instruct V0.1" },
    { id: "upstage/solar-10.7b-instruct", name: "Solar 10.7b Instruct" },
    { id: "utter-project/eurollm-9b-instruct", name: "Eurollm 9b Instruct" },
    { id: "writer/palmyra-creative-122b", name: "Palmyra Creative 122b" },
    { id: "writer/palmyra-fin-70b-32k", name: "Palmyra Fin 70b 32k" },
    { id: "writer/palmyra-med-70b", name: "Palmyra Med 70b" },
    { id: "writer/palmyra-med-70b-32k", name: "Palmyra Med 70b 32k" },
    { id: "yentinglin/llama-3-taiwan-70b-instruct", name: "Llama 3 Taiwan 70b Instruct" },
    { id: "z-ai/glm-5.1", name: "Glm 5.1" },
    { id: "z-ai/glm4.7", name: "Glm4.7" },
    { id: "z-ai/glm5", name: "Glm5" },
    { id: "zyphra/zamba2-7b-instruct", name: "Zamba2 7b Instruct" },
  ],

  // TTS entries are loaded from ttsModels.js via buildTtsProviderModels()
  ...buildTtsProviderModels(),

  // Image providers
  nanobanana: [
    { id: "nanobanana-flash", name: "NanoBanana Flash", type: "image", params: ["n", "size"] },
    { id: "nanobanana-pro", name: "NanoBanana Pro", type: "image", params: ["n", "size"] },
  ],
  sdwebui: [
    { id: "stable-diffusion-v1-5", name: "Stable Diffusion v1.5", type: "image", params: ["n", "size"] },
    { id: "sdxl-base-1.0", name: "SDXL Base 1.0", type: "image", params: ["n", "size"] },
  ],
  comfyui: [
    { id: "flux-dev", name: "FLUX Dev", type: "image", params: ["n", "size"] },
    { id: "sdxl", name: "SDXL", type: "image", params: ["n", "size"] },
  ],
  huggingface: [
    { id: "black-forest-labs/FLUX.1-schnell", name: "FLUX.1 Schnell", type: "image", params: [] },
    { id: "stabilityai/stable-diffusion-xl-base-1.0", name: "SDXL Base 1.0", type: "image", params: [] },
  ],
};

// Helper functions
export function getProviderModels(aliasOrId) {
  return PROVIDER_MODELS[aliasOrId] || [];
}

export function getDefaultModel(aliasOrId) {
  const models = PROVIDER_MODELS[aliasOrId];
  return models?.[0]?.id || null;
}

export function isValidModel(aliasOrId, modelId, passthroughProviders = new Set()) {
  if (passthroughProviders.has(aliasOrId)) return true;
  const models = PROVIDER_MODELS[aliasOrId];
  if (!models) return false;
  return models.some(m => m.id === modelId);
}

export function findModelName(aliasOrId, modelId) {
  const models = PROVIDER_MODELS[aliasOrId];
  if (!models) return modelId;
  const found = models.find(m => m.id === modelId);
  return found?.name || modelId;
}

export function getModelTargetFormat(aliasOrId, modelId) {
  const models = PROVIDER_MODELS[aliasOrId];
  if (!models) return null;
  const found = models.find(m => m.id === modelId);
  return found?.targetFormat || null;
}

// OAuth providers that use short aliases (everything else: alias = id)
const OAUTH_ALIASES = {
  claude: "cc",
  codex: "cx",
  "gemini-cli": "gc",
  qwen: "qw",
  iflow: "if",
  antigravity: "ag",
  github: "gh",
  kiro: "kr",
  cursor: "cu",
  "kimi-coding": "kmc",
  kilocode: "kc",
  cline: "cl",
  opencode: "oc",
  vertex: "vertex",
  "vertex-partner": "vertex-partner",
};

// Derived from PROVIDERS — no need to maintain manually
export const PROVIDER_ID_TO_ALIAS = Object.fromEntries(
  Object.keys(PROVIDERS).map(id => [id, OAUTH_ALIASES[id] || id])
);

export function getModelsByProviderId(providerId) {
  const alias = PROVIDER_ID_TO_ALIAS[providerId] || providerId;
  return PROVIDER_MODELS[alias] || [];
}

// Get strip list for a model entry (explicit opt-in only)
// Returns array of content types to strip, e.g. ["image", "audio"]
export function getModelStrip(alias, modelId) {
  const entry = PROVIDER_MODELS[alias]?.find(m => m.id === modelId);
  return entry?.strip || [];
}
